In [8]:
import numpy as np
import time

In [3]:
# A = 0 ... 1 000 000 000 
# B = 0 ... 1 000 000 000
# C = 0 2 4 ... 2 000 000 000

In [8]:


N = 10_000_000  # 10 milyon

def python_version():
    start_time = time.time()
    A = list(range(N))
    B = list(range(N))
    C = [A[i] + B[i] for i in range(len(A))]
    end_time = time.time()
    sure = end_time - start_time
    print(f'Python versiyonu çalışma süresi: {sure:.4f} saniye')

python_version()


Python versiyonu çalışma süresi: 0.9402 saniye


In [16]:
N = 10_000_000  # test için makul bir boyut

def numpy_version():
    start_time = time.time()
    A = np.arange(N)
    B = np.arange(N)
    C = A + B
    end_time = time.time()
    sure = end_time - start_time
    print(f'NumPy versiyonu çalışma süresi: {sure:.4f} saniye')

numpy_version()


NumPy versiyonu çalışma süresi: 0.0506 saniye


In [14]:
python_version()
numpy_version()

Python versiyonu çalışma süresi: 0.8634 saniye
NumPy versiyonu çalışma süresi: 0.0438 saniye


In [17]:
list1 = [1,2,3,4,5,6,7]
arr1 = np.array(list1)

In [18]:
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
arr1.astype(float)

array([1., 2., 3., 4., 5., 6., 7.])

In [21]:
a = np.arange(0,25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
a[3]

np.int64(3)

In [24]:
b = np.arange(0,151,25)
b

array([  0,  25,  50,  75, 100, 125, 150])

In [25]:
c = np.arange(100, -1, -10)
c

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10,   0])

In [27]:
# Sıfırlardan oluşan bir dizi
zeros = np.zeros(10).astype(int)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
ones = np.ones(8).astype(int)
ones

array([1, 1, 1, 1, 1, 1, 1, 1])

In [33]:
# repeat(sayi, kac_tane)

rp = np.repeat(36,10)
rp

array([36, 36, 36, 36, 36, 36, 36, 36, 36, 36])

In [34]:
d = np.array([1,2,3,4])
rp_1 = np.repeat(d,3)
rp_1

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [36]:
sayilar = list(range(1,21))
tek_sayilar = []
for i in sayilar:
    if i % 2 == 1:
        tek_sayilar.append(i)
tek_sayilar        

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [38]:
np_sayilar = np.arange(1,21)
tek_numpy = np_sayilar[np_sayilar % 2 ==1]
tek_numpy

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [40]:
# Linspace(başlangıc, bitis, adet) : başlangıçtan bitişe kadar kaç adet sayı istniyorsa 
# eşit olacak şekilde böler.

lns = np.linspace(20, 30, 3).astype(int)
lns

array([20, 25, 30])

In [42]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [43]:
np.random.random(4)

array([0.7187251 , 0.14274075, 0.75778708, 0.23541102])

In [44]:
np.random.randint(100,350,50)

array([188, 288, 331, 139, 209, 128, 177, 221, 343, 312, 313, 158, 147,
       339, 194, 150, 100, 129, 220, 158, 252, 238, 204, 211, 131, 280,
       113, 234, 342, 192, 328, 149, 330, 162, 201, 317, 162, 242, 289,
       128, 316, 101, 250, 346, 327, 128, 331, 125, 233, 189], dtype=int32)

In [45]:
np.random.seed(200)
np.random.randint(0,500,10)

array([282, 105, 272, 324, 298, 183, 332,  79, 345,  14], dtype=int32)

In [46]:
np.random.randint(0,500,10)

array([219, 185,  89, 139, 390,  42, 312,   1,   7,  51], dtype=int32)

In [48]:
a = np.random.randint(100,450,65)
a

array([301, 243, 229, 338, 379, 185, 363, 410, 372, 391, 344, 259, 287,
       417, 376, 185, 342, 228, 231, 155, 284, 103, 261, 300, 228, 280,
       446, 289, 426, 199, 176, 286, 424, 290, 152, 106, 355, 296, 292,
       445, 278, 197, 316, 235, 285, 197, 251, 268, 382, 293, 181, 427,
       318, 100, 273, 182, 138, 393, 255, 320, 334, 243, 437, 129, 213],
      dtype=int32)

In [49]:
a.max()

np.int32(446)

In [50]:
a.min()

np.int32(100)

In [51]:
a.sum()

np.int64(18318)

In [52]:
a.mean()

np.float64(281.81538461538463)

In [53]:
# standart sapma
a.std()

np.float64(90.64111688966501)

In [61]:
A = np.array([[1,11,3],[4,15,6],[7,8,19]])
A

array([[ 1, 11,  3],
       [ 4, 15,  6],
       [ 7,  8, 19]])

In [62]:
A.sum()

np.int64(74)

In [63]:
np.amin(A,axis=0)

array([1, 8, 3])

In [64]:
np.amax(A,axis=0)

array([ 7, 15, 19])

In [65]:
np.amin(A,axis=1)

array([1, 4, 7])

In [66]:
np.amax(A,axis=1)

array([11, 15, 19])

In [67]:
b = np.random.randint(10,20,30)
b

array([18, 13, 10, 17, 18, 14, 13, 16, 10, 17, 19, 11, 15, 14, 11, 14, 15,
       17, 12, 10, 19, 17, 10, 15, 14, 16, 16, 19, 16, 17], dtype=int32)

In [71]:
b[1:5]

array([13, 10, 17, 18], dtype=int32)

In [73]:
# sondan 5. indexten son elemandan 1 index geride olan tüm sayıları alın

b[-5:-1]

array([16, 16, 19, 16], dtype=int32)

In [74]:
# son 5 veri

b[-5:]

array([16, 16, 19, 16, 17], dtype=int32)

In [79]:
# ilk 6 veri
b[0:6]
b[:6]

array([18, 13, 10, 17, 18, 14], dtype=int32)

In [81]:
d = np.arange(21)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [82]:
# d dizisi içerisinde çift sayıların yerine 5 yazan kodu yazınn

r = np.where(d %2==0, 5, d)
r

array([ 5,  1,  5,  3,  5,  5,  5,  7,  5,  9,  5, 11,  5, 13,  5, 15,  5,
       17,  5, 19,  5])

In [83]:
a = np.array([10,25,36,np.nan, 69, 85, np.nan])
a

array([10., 25., 36., nan, 69., 85., nan])

In [85]:
np.isnan(a)

array([False, False, False,  True, False, False,  True])

In [86]:
a[np.isnan(a)] = 25

In [87]:
a

array([10., 25., 36., 25., 69., 85., 25.])

In [91]:
c1 = np.arange(10,61,10)
c2 = np.array([12,25,30,44,60,55,50])

In [92]:
c1

array([10, 20, 30, 40, 50, 60])

In [93]:
c2

array([12, 25, 30, 44, 60, 55, 50])

In [94]:
np.setdiff1d(c1,c2)

array([10, 20, 40])

In [95]:
np.setdiff1d(c2,c1)

array([12, 25, 44, 55])

In [96]:
c2

array([12, 25, 30, 44, 60, 55, 50])

In [97]:
# verileri ters şekilde sıralama

c2[::-1]

array([50, 55, 60, 44, 30, 25, 12])

In [98]:
np.flip(c2)

array([50, 55, 60, 44, 30, 25, 12])

In [101]:
a3 = np.array([[3,4,8,7],[11,24,10,85],[35,5,47,2]])
a3

array([[ 3,  4,  8,  7],
       [11, 24, 10, 85],
       [35,  5, 47,  2]])

In [102]:
a3[::-1,]

array([[35,  5, 47,  2],
       [11, 24, 10, 85],
       [ 3,  4,  8,  7]])

In [103]:
a3[:,::-1]

array([[ 7,  8,  4,  3],
       [85, 10, 24, 11],
       [ 2, 47,  5, 35]])

In [104]:
a3[::-1,::-1]

array([[ 2, 47,  5, 35],
       [85, 10, 24, 11],
       [ 7,  8,  4,  3]])

In [106]:
# reshape()

p1 = np.arange(0,121).reshape(11,11)
p1

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [108]:
a1 = [5,6,7]
a2 = [4,3,2]
a3 = np.multiply(a1,a2)
a3

array([20, 18, 14])

In [109]:
a4 = np.array([5,6,7])
a5 = np.array([4,3,2])

a4 * a5

array([20, 18, 14])

In [110]:
M = np.random.randint(0,1000,100).reshape(10,10)
M

array([[512, 882, 370, 363, 272, 381, 200, 159, 284, 339],
       [596, 648, 209,  76, 783, 989, 833, 984, 832, 861],
       [  2,  67, 644, 743, 829, 190, 315, 460, 664,  77],
       [ 17, 158, 333, 884, 104,  90, 564, 998, 387, 670],
       [707, 656,  84, 943, 930, 554,  10, 485, 825, 507],
       [821,  21, 984, 143, 728, 414, 766, 308, 369, 781],
       [386, 545, 872, 795, 875, 586, 831, 853, 191, 792],
       [223, 405, 426, 132, 319, 205, 542, 220, 102, 539],
       [292, 566, 331, 939, 624, 519, 367, 938,  24, 292],
       [804, 106, 527, 720, 151, 210, 100, 968,  26, 697]], dtype=int32)

In [113]:
# 500 den büyük olan değerleri ayrı listede tut

filtered = M[M>500]
filtered

array([512, 882, 596, 648, 783, 989, 833, 984, 832, 861, 644, 743, 829,
       664, 884, 564, 998, 670, 707, 656, 943, 930, 554, 825, 507, 821,
       984, 728, 766, 781, 545, 872, 795, 875, 586, 831, 853, 792, 542,
       539, 566, 939, 624, 519, 938, 804, 527, 720, 968, 697], dtype=int32)

In [114]:
# birim matrix(identity) : ana köşegenleri birlerden ve diğer elemanları sıfırlardan oluşan n * n boyutlu bir kare matrixtir

I = np.eye(8).astype(int)
I

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [115]:
# diagonal matris
D = np.diag(np.arange(1,11))
D

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10]])

In [117]:
D1 = np.diag([3,5,7,8])
D1

array([[3, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 8]])

In [118]:
M1 = np.random.randn(5,5)
M1

array([[-0.40408192, -1.638067  , -0.15125239,  0.90744408,  0.0673945 ],
       [ 0.69049189, -0.06996847,  0.74731893, -0.30642407,  0.18199109],
       [-0.07213603,  2.21796653,  0.2584544 , -0.73603076,  0.31125086],
       [-0.11879521,  0.77047831, -1.14883292, -0.27289366, -0.12485667],
       [ 0.62675835,  1.15805552,  0.35786937,  0.52423795, -0.88974969]])

In [120]:
# üst üçgen matrisi

U = np.triu(M1)
U

array([[-0.40408192, -1.638067  , -0.15125239,  0.90744408,  0.0673945 ],
       [ 0.        , -0.06996847,  0.74731893, -0.30642407,  0.18199109],
       [ 0.        ,  0.        ,  0.2584544 , -0.73603076,  0.31125086],
       [ 0.        ,  0.        ,  0.        , -0.27289366, -0.12485667],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.88974969]])

In [121]:
L = np.tril(M1)
L

array([[-0.40408192,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.69049189, -0.06996847,  0.        ,  0.        ,  0.        ],
       [-0.07213603,  2.21796653,  0.2584544 ,  0.        ,  0.        ],
       [-0.11879521,  0.77047831, -1.14883292, -0.27289366,  0.        ],
       [ 0.62675835,  1.15805552,  0.35786937,  0.52423795, -0.88974969]])

In [122]:
M2 = np.random.randint(10,45,9).reshape(3,3)
M2

array([[21, 44, 11],
       [10, 25, 23],
       [19, 18, 28]], dtype=int32)

In [123]:
np.transpose(M2)

array([[21, 10, 19],
       [44, 25, 18],
       [11, 23, 28]], dtype=int32)

In [125]:
# determinant alma 
np.linalg.det(M2)

np.float64(9668.99999999999)

In [126]:
# Elimizde 1 haftalık hava sıcaklığı verisi mevcut.
# Bu sıcaklık bilgilerine dayanarak ortalama sıcaklığı hesapla.

sicakliklar = [35,30,25,36,30,25,40]
sicakliklar_np = np.array(sicakliklar)
ortalama = sicakliklar_np.mean()
print(f'Ortalama sıcaklık : {ortalama} C dir')

Ortalama sıcaklık : 31.571428571428573 C dir


In [130]:
# Hisse senedi uygulaması 
# Getiri = ((bugünkü fiyat - dünkü fiyat)/ dünkü fiyat*100

prices = np.array([1000,1020,1100,1045,1150,1200,1100])
getiriler_farki = np.diff(prices)
result = getiriler_farki / prices[:-1] *100 
print(f'Günlük getiri (%) {result}')
print(f'Ortalama günlük getirisi : {np.mean(result)} &')

Günlük getiri (%) [ 2.          7.84313725 -5.         10.04784689  4.34782609 -8.33333333]
Ortalama günlük getirisi : 1.8175794830795506 &


In [136]:
# Başlangıç nüfusu 10 milyon olan ülkenin yıllık büyüme oranı v2 dir. 
# 10 yıllık nüfus tahmini yapın.
# P(t) = P0* e^rt

baslangic_nufusu = 10000000
buyume_orani = 0.02
yillar = np.arange(1,11)
populasyon = baslangic_nufusu * np.exp(buyume_orani * yillar)
print(f'10 yıllık nüfus tahmini : ')
populasyon

10 yıllık nüfus tahmini : 


array([10202013.40026756, 10408107.74192388, 10618365.4654536 ,
       10832870.67674959, 11051709.18075648, 11274968.51579376,
       11502737.98857227, 11735108.7099181 , 11972173.6312181 ,
       12214027.5816017 ])