In [1]:
# Soru 1 – Liste Metotları

In [2]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]

# Tekrar edenleri sil
benzersiz_notlar = list(set(notlar))
print("Benzersiz notlar:", benzersiz_notlar)

# En yüksek ve en düşük not
en_yuksek = max(notlar)
en_dusuk = min(notlar)
print("En yüksek:", en_yuksek, "En düşük:", en_dusuk)

# Notları küçükten büyüğe sırala
sirali_notlar = sorted(notlar)
print("Sıralı notlar:", sirali_notlar)


Benzersiz notlar: [100, 92, 85, 76]
En yüksek: 100 En düşük: 76
Sıralı notlar: [76, 76, 85, 85, 92, 92, 92, 100]


In [3]:
# Soru 2 – Armstrong Sayısı

In [4]:
# Armstrong sayısı: Her basamağının küplerinin toplamı kendisine eşit olan sayılar. 
# Örn: 153 → 1³+5³+3³ = 153

In [6]:
def armstrong_mi(sayi):
    basamaklar = [int(d) for d in str(sayi)]
    return sum(d**3 for d in basamaklar) == sayi

print(armstrong_mi(153))  
print(armstrong_mi(123))  


True
False


In [7]:
# Soru 3 – Kümeler

In [8]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

# Ortak diller
print("Ortak:", A & B)

# Sadece A’da olanlar
print("Sadece A:", A - B)

# Birleşim alfabetik
print("Birleşim:", sorted(A | B))


Ortak: {'Python', 'SQL'}
Sadece A: {'R', 'Java'}
Birleşim: ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [9]:
# Soru 4 – Modüller

In [10]:
import random
import statistics

rastgele_sayilar = [random.randint(1, 100) for _ in range(10)]
ortalama = statistics.mean(rastgele_sayilar)
std_sapma = statistics.stdev(rastgele_sayilar)

print("Rastgele sayılar:", rastgele_sayilar)
print("Ortalama:", ortalama, "Standart sapma:", std_sapma)


Rastgele sayılar: [75, 56, 76, 67, 85, 40, 26, 65, 90, 14]
Ortalama: 59.4 Standart sapma: 25.307881951852252


In [11]:
# Soru 5 – Fonksiyonlar

In [12]:
from collections import Counter

def kelime_sayaci(metin):
    kelimeler = metin.split()
    toplam = len(kelimeler)
    en_uzun = max(kelimeler, key=len)
    en_sik = Counter(kelimeler).most_common(1)[0][0]
    return toplam, en_uzun, en_sik

print(kelime_sayaci("Python veri bilimi ile veri analizi yapıyoruz"))


(7, 'yapıyoruz', 'veri')


In [13]:
#Soru 6 – Gömülü Fonksiyonlar

In [14]:
sayilar = [5, 12, 7, 18, 24, 3, 16]

ciftler = list(filter(lambda x: x % 2 == 0, sayilar))
kareler = list(map(lambda x: x**2, ciftler))
sirali_kareler = sorted(kareler, reverse=True)

print("Çiftler:", ciftler)
print("Kareler:", kareler)
print("Sıralı kareler:", sirali_kareler)


Çiftler: [12, 18, 24, 16]
Kareler: [144, 324, 576, 256]
Sıralı kareler: [576, 324, 256, 144]


In [15]:
# Soru 7 – Lambda

In [16]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
sirali = sorted(kelimeler, key=lambda x: len(x))
print(sirali)


['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [17]:
# Soru 8 – Metodlar

In [18]:
def rakam_toplami(metin):
    return sum(int(c) for c in metin if c.isdigit())

print(rakam_toplami("abc12def3"))  # 1+2+3=6 değil, dikkat: iki basamaklılar için ayrı işleme gerek


6


In [19]:
# Soru 9 ve 10 – Numpy (Opsiyonel)

In [20]:
import numpy as np

# Soru 9
dizi = np.random.randint(0, 51, 10)
print(dizi, dizi.mean(), dizi.std(), dizi.max())

# Soru 10
matris = np.random.rand(5,5)
sutun_ort = matris.mean(axis=0)
binary = (matris > 0.5).astype(int)
print("Sütun ortalamaları:", sutun_ort)
print("Binary matris:\n", binary)


[29  5  4  4  9 38  5 37 36 46] 21.3 16.407620180879373 46
Sütun ortalamaları: [0.48979044 0.686809   0.42912475 0.61537656 0.45381263]
Binary matris:
 [[1 1 0 1 1]
 [1 1 1 1 0]
 [1 0 0 1 0]
 [0 1 0 0 0]
 [0 1 1 0 1]]


In [21]:
# Proje – Kitap Satış Analiz Sistemi
# 1️ Fonksiyonlar

In [22]:
kitaplar = [
    {"isim": "Veri Bilimi 101", "yazar": "Ali", "tur": "Bilim", "satis": 1200, "yil": 2021},
    {"isim": "Python ile Yapay Zeka", "yazar": "Ayşe", "tur": "Bilim", "satis": 950, "yil": 2020},
    {"isim": "İstatistik Temelleri", "yazar": "Ali", "tur": "Akademik", "satis": 700, "yil": 2019},
    {"isim": "Makine Öğrenmesi", "yazar": "Can", "tur": "Bilim", "satis": 1800, "yil": 2022},
    {"isim": "Veri Görselleştirme", "yazar": "Deniz", "tur": "Sanat", "satis": 400, "yil": 2018},
    {"isim": "Matematiksel Modelleme", "yazar": "Ali", "tur": "Akademik", "satis": 1500, "yil": 2021},
    {"isim": "Bilgi Toplumu", "yazar": "Ayşe", "tur": "Sosyal", "satis": 600, "yil": 2022}
]

def en_cok_satan(kitaplar):
    return max(kitaplar, key=lambda k: k['satis'])

def yazar_satislari(kitaplar):
    satis_dict = {}
    for k in kitaplar:
        satis_dict[k['yazar']] = satis_dict.get(k['yazar'], 0) + k['satis']
    return satis_dict

print(en_cok_satan(kitaplar))
print(yazar_satislari(kitaplar))


{'isim': 'Makine Öğrenmesi', 'yazar': 'Can', 'tur': 'Bilim', 'satis': 1800, 'yil': 2022}
{'Ali': 3400, 'Ayşe': 1550, 'Can': 1800, 'Deniz': 400}


In [23]:
# 2 Liste ve Küme İşlemleri

In [24]:
turler = set(k['tur'] for k in kitaplar)
fazla_satan = [k['isim'] for k in kitaplar if k['satis'] > 1000]

print(turler)
print(fazla_satan)


{'Akademik', 'Bilim', 'Sanat', 'Sosyal'}
['Veri Bilimi 101', 'Makine Öğrenmesi', 'Matematiksel Modelleme']


In [25]:
# 3 Lambda / Map / Filter

In [26]:
kitap_2020_sonra = list(filter(lambda k: k['yil'] > 2020, kitaplar))
satis_arti = list(map(lambda k: k['satis']*1.1, kitaplar))
sirali_kitaplar = sorted(kitaplar, key=lambda k: k['satis'], reverse=True)

print(kitap_2020_sonra)
print(satis_arti)
print([k['isim'] for k in sirali_kitaplar])


[{'isim': 'Veri Bilimi 101', 'yazar': 'Ali', 'tur': 'Bilim', 'satis': 1200, 'yil': 2021}, {'isim': 'Makine Öğrenmesi', 'yazar': 'Can', 'tur': 'Bilim', 'satis': 1800, 'yil': 2022}, {'isim': 'Matematiksel Modelleme', 'yazar': 'Ali', 'tur': 'Akademik', 'satis': 1500, 'yil': 2021}, {'isim': 'Bilgi Toplumu', 'yazar': 'Ayşe', 'tur': 'Sosyal', 'satis': 600, 'yil': 2022}]
[1320.0, 1045.0, 770.0000000000001, 1980.0000000000002, 440.00000000000006, 1650.0000000000002, 660.0]
['Makine Öğrenmesi', 'Matematiksel Modelleme', 'Veri Bilimi 101', 'Python ile Yapay Zeka', 'İstatistik Temelleri', 'Bilgi Toplumu', 'Veri Görselleştirme']


In [33]:
import random
import statistics

kitaplar = [
    {"isim": "Veri Bilimi 101", "yazar": "Ali", "tur": "Bilim", "satis": 1200, "yil": 2021},
    {"isim": "Python ile Yapay Zeka", "yazar": "Ayşe", "tur": "Bilim", "satis": 950, "yil": 2020},
    {"isim": "İstatistik Temelleri", "yazar": "Ali", "tur": "Akademik", "satis": 700, "yil": 2019},
    {"isim": "Makine Öğrenmesi", "yazar": "Can", "tur": "Bilim", "satis": 1800, "yil": 2022},
    {"isim": "Veri Görselleştirme", "yazar": "Deniz", "tur": "Sanat", "satis": 400, "yil": 2018},
    {"isim": "Matematiksel Modelleme", "yazar": "Ali", "tur": "Akademik", "satis": 1500, "yil": 2021},
    {"isim": "Bilgi Toplumu", "yazar": "Ayşe", "tur": "Sosyal", "satis": 600, "yil": 2022}
]

# 1️ Train/Test ayırımı (%70 train, %30 test)
train_size = int(len(kitaplar) * 0.7)
train = random.sample(kitaplar, train_size)
test = [k for k in kitaplar if k not in train]

print("Train seti:", [k['isim'] for k in train])
print("Test seti:", [k['isim'] for k in test])

# 2️ Train setinden yazarların ortalama satışlarını hesapla
yazar_satislari_train = {}
for k in train:
    yazar_satislari_train.setdefault(k['yazar'], []).append(k['satis'])

yazar_ortalama_train = {yazar: sum(satislar)/len(satislar) 
                        for yazar, satislar in yazar_satislari_train.items()}

print("Yazar ortalama satışları (train):", yazar_ortalama_train)

# 3️ Test setinde, satışları yazar ortalamasının üzerinde olan kitapları bul
test_ustu_satislar = [k['isim'] for k in test 
                      if k['satis'] > yazar_ortalama_train.get(k['yazar'], 0)]

print("Test setinde ortalamanın üzerinde satan kitaplar:", test_ustu_satislar)

# 4️ İstatistiksel özet (opsiyonel)
train_satislar = [k['satis'] for k in train]
test_satislar = [k['satis'] for k in test]

print("Train ortalama satış:", statistics.mean(train_satislar))
print("Test ortalama satış:", statistics.mean(test_satislar))


Train seti: ['Bilgi Toplumu', 'Veri Bilimi 101', 'İstatistik Temelleri', 'Veri Görselleştirme']
Test seti: ['Python ile Yapay Zeka', 'Makine Öğrenmesi', 'Matematiksel Modelleme']
Yazar ortalama satışları (train): {'Ayşe': 600.0, 'Ali': 950.0, 'Deniz': 400.0}
Test setinde ortalamanın üzerinde satan kitaplar: ['Python ile Yapay Zeka', 'Makine Öğrenmesi', 'Matematiksel Modelleme']
Train ortalama satış: 725
Test ortalama satış: 1416.6666666666667
